os: linux
language: node_js
mode_js:
    - 12.4.0
services:
    - docker
    
before_install:
    - docker build -t anilverma/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anilverma/docker-react npm run test
    
    
    
    