sudo: required
services:
    - docker
    
before_install:
    - docker build -t anilverma/docker-react -f Dockerfile.dev .

script:
    - docker run anilverma/docker-react npm run test -- --coverage
    
    
    
    